[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.black]
include = '\.pyi?$'

[tool.isort]
profile = 'black'

[tool.mypy]
files = [
    'src/**/*.py',
    'tests/**/*.py'
]
